### ISSUE TITLE
SingleValue source

### ISSUE THREAD

**Issue by Sroka** [FrangSierra/Rx2Firebase#15]
Thanks for porting this to RxJava2, will be moving my project to use this library soon :) 

After using Firebase for some time one of most painful limitations for me was inability to choose source (Cache or Network) for SingleValue listeners  after setting
`FirebaseDatabase.getInstance().setPersistenceEnabled(true)`

This is well described here:
https://stackoverflow.com/questions/35454652/how-to-bypass-the-firebase-cache-to-refresh-data-in-android-app?noredirect=1&lq=1
and here:
https://groups.google.com/forum/#!msg/firebase-talk/ptTtEyBDKls/XbNKD_K8CQAJ

Since firebase team didn't care to acknowledge that this is an issue I guess we have to stick with mock object workaround from first answer on SO link above.

I know that this library is only meant to be a wrapper around Firebase but having overloaded observeSingleValueEvent listener method that lets you specify source would be great. Would you accept PR if I add and properly test this?

**Comment by FrangSierra** [comment]
Ofc I will, feel free to do PR's. Anyway I will add it in the next release, is just a overloaded method with a boolean. So it will be easy :)

**Comment by FrangSierra** [comment]
After give a look to how it is implemented in the last commit. Add this no have so much sense cause you are providing the instance of the database, so you are the one who needs to enable persistence before or after. Same happend with the queries, if u want to enable `SyncMode()` on them you should do it before.

Anyway, feel free to do a PR with your idea about how to implement it and I will give it a loot :+1:
