### ISSUE TITLE
No Doc on How to Use ChildEvents

### ISSUE THREAD

**Issue by po10cio** [FrangSierra/Rx2Firebase#16]
Your doc does not show how to properly use childEvents, it only has SingleValeEvents every where, could you review it.

**Comment by VirgilHub** [comment]
childEvents:

RxFirebaseDatabase
        .observeChildEvent('Path Query', 'Your Backpressure Strategy')
        .subscribeOn('Choose Scheduler')
        .map(new Function<RxFirebaseChildEvent<DataSnapshot>, 'Your Class'>() {
          @Override public 'Your Class' apply(
              @io.reactivex.annotations.NonNull RxFirebaseChildEvent<DataSnapshot> dataSnapshot) throws Exception {
            String key = dataSnapshot.getKey();
            EventType type = dataSnapshot.getEventType(); // ADD, REMOVE ...
            DataSnapshot value = dataSnapshot.getValue();
            'Your Class' item = value.getValue('Your Class'.class);
            return 'Your Class Instance';
          }
        });

**Comment by m-reid** [comment]
You would only use `childEvents` when observing a list of items(See the readme under the `RxFirebaseRecyclerAdapter` section and @VirgilHub's answer). 

This library is only a wrapper to make Rx implementation easier. It still requires an understanding of the underlying Firebase API. [Read this](https://firebase.google.com/docs/database/android/lists-of-data) on how and when to use `valueEvents` vs `childEvents`.

**Comment by FrangSierra** [comment]
Yes, as @m-reid says, the library is a wrapper, also, all methods are quite good documented with javadoc. You can easily see how it works if you make a call to the method.

For user child events you can use `RxFirebaseRecylerAdapter` or do your own abstraction. Each call of `observeChildEvent` will emit `RxFirebaseChildEvent<T>` which are a wrapper of `DataSnapshot` typed with an `EventType` to know which kind of event is:

``` 
public enum EventType {
      ADDED,
      CHANGED,
      REMOVED,
      MOVED
}
```

With this 2 things you can whatever you want in your view or database :)
