### ISSUE TITLE
Problem after upgrading gradle to 3.0.0-alpha1 and changing maven address

### ISSUE THREAD

**Issue by stMayhem** [FrangSierra/Rx2Firebase#21]
Error:Could not find com.github.frangsierra:rx2firebase:1.1.1.
Searched in the following locations:
    file:/C:/Android/sdk/extras/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.pom
    file:/C:/Android/sdk/extras/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.jar
    file:/C:/Android/sdk/extras/google/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.pom
    file:/C:/Android/sdk/extras/google/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.jar
    file:/C:/Android/sdk/extras/android/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.pom
    file:/C:/Android/sdk/extras/android/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.jar
    file:/C:/Android/Android Studio/gradle/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.pom
    file:/C:/Android/Android Studio/gradle/m2repository/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.jar
    https://jcenter.bintray.com/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.pom
    https://jcenter.bintray.com/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.jar
    https://maven.google.com/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.pom
    https://maven.google.com/com/github/frangsierra/rx2firebase/1.1.1/rx2firebase-1.1.1.jar
Required by:
    project :app

It happened after changing maven address to 'https://maven.google.com'  and upgrading gradle version to 3.0.0-alpha1

**Comment by FrangSierra** [comment]
The library is uploaded to the url "https://jitpack.io" maven repository, You can have both at your gradle.
allprojects {
    repositories {
        mavenLocal()
        maven { url "https://jitpack.io" }
       maven { url "https://maven.google.com" }
        jcenter()
    }
}

**Comment by stMayhem** [comment]
And why can not you upload the library on the new server?

**Comment by FrangSierra** [comment]
Cause is the official repository for Google, and not an open one
