### ISSUE TITLE
handle exception on signinwithemailandpassword

### ISSUE THREAD

**Issue by GurtekSingh** [FrangSierra/Rx2Firebase#24]
i can't handle the exception when a user try to login which is not yet created it throws exception even i put in try catch help me to slove this problem hwo i suppose to handle exception thanks in advance

RxFirebaseAuth.signInWithEmailAndPassword(auth, email, password)
                    .filter(result -> result.getUser() != null)
                    .subscribe(result -> {
                        dataSaveRepo.getUserData(result);

                    }));

**Comment by FrangSierra** [comment]
You should implement another the exception handler inside the subscribe:
```
RxFirebaseAuth.signInWithEmailAndPassword(authInstance, email, password)
                .filter { authResult -> authResult.user != null }
                .subscribe({ authResult -> dispatcher.dispatchOnUi(AuthenticationStatusChangedAction(LoginStatus.LOGGED, authResult.user)) }
                ) { dispatcher.dispatchOnUi(AuthenticationErrorAction(it)) }
```
It's basic Rx Java management, you can read more about it in https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0
