### ISSUE TITLE
Changed behaviour for RxFirebaseDatabase.observeValueEvent

### ISSUE THREAD

**Issue by gswierczynski** [FrangSierra/Rx2Firebase#30]
Hi,

Last version added check datasnapshot.exists() in the above method. As long as adding that in observeSingleValueEvent makes sense (probably everyone using lib were filtering on it anyway), adding this in observeValueEvent changes behaviour significantly.

There is no way to know now if the passed DatabaseReference exists or not (to act accordingly).
IMO it should be left to the lib user to deal with that (maybe warn in java doc).

Cheers,
Greg.

**Comment by FrangSierra** [comment]
Hi @gswierczynski ,

you can know if the dataSnapshot exist or not just listening the `onComplete` callback, if the `DataSnapshot` doesn't exist, `onComplete` will be call, but `onSucess` will be not.

**Comment by gswierczynski** [comment]
Hi @FrangSierra,

Thanks for the good work.

I don't think onComplete will be called for the observeValueEvent.

```java
return Flowable.create(new FlowableOnSubscribe<DataSnapshot>() {
         @Override
         public void subscribe(final FlowableEmitter<DataSnapshot> emitter) throws Exception {
            final ValueEventListener valueEventListener = new ValueEventListener() {
               @Override
               public void onDataChange(DataSnapshot dataSnapshot) {
                  if (dataSnapshot.exists())
                     emitter.onNext(dataSnapshot);
               }

               @Override
               public void onCancelled(final DatabaseError error) {
                  emitter.onError(new RxFirebaseDataException(error));
               }
            };
            emitter.setCancellable(new Cancellable() {
               @Override
               public void cancel() throws Exception {
                  query.removeEventListener(valueEventListener);
               }
            });
            query.addValueEventListener(valueEventListener);
         }
      }, strategy);
```

**Comment by FrangSierra** [comment]
You are totally right, I missunderstood it with `observeSingleValueEvent` which uses an `onComplete` call too.

**Comment by FrangSierra** [comment]
I will look how to resolve it, cause if I delete the `dataSnapshot.exists()` the `GenericTypedDataSnapshotMapper` will throw NPE in that case.

If you have any idea, please, feel free to do a PR and we can look together for a solution.

Have a good day.

**Comment by akalinxy** [comment]
Maybe wrap Datasnapshot in optional?
