### ISSUE TITLE
Support Firebase Firestore 

### ISSUE THREAD

**Issue by tspoke** [FrangSierra/Rx2Firebase#31]
Hi,

Thank you for your library, it helps a lot :)

Yesterday Google released the Firebase Firestore project (beta). I think it could be very interesting to integrate it in your library too.

**Comment by FrangSierra** [comment]
I will start on it this afternoon, don't worry! Soon there will be an update, I'm the first one who want's to move to Firestore ^^

**Comment by FrangSierra** [comment]
Just released the `1.4-beta.1` version with the Firestore integration

**Comment by tspoke** [comment]
Thank you @FrangSierra , I will give it a try tomorrow :)
