### ISSUE TITLE
RxFirebaseDatabase.observeValueEvent Crashes

### ISSUE THREAD

**Issue by eMdOS** [FrangSierra/Rx2Firebase#38]
`RxFirebaseDatabase.observeValueEvent` throws an error when the user signs out from Firebase.

```
io.reactivex.exceptions.UndeliverableException: RxFirebaseDataException{error=DatabaseError: This client does not have permission to perform this operation}
```

**Comment by FrangSierra** [comment]
That's not an error from the library. That error says that you still listening that observable when the user sign out. If you have some rules in your database, the `auth state` of your user after sign out will be null. So you will not be able to continue listening changes on your observables.

To avoid these you should dispose the observable before sign out, or modify your rules.
