### ISSUE TITLE
Please add proguard rules

### ISSUE THREAD

**Issue by androidovshchik** [FrangSierra/Rx2Firebase#40]
For today i wrote only one dontwarn rule for release build
`-dontwarn durdinapps.rxfirebase2.**`

**Comment by FrangSierra** [comment]
I added a proguard rules in the latest release, after research. You doesnt need any kind of obfuscation unless you are using FirebaseDatabase, in which case you should add : 
`-keepattributes Signature`
Gson uses generic type information stored in a class file when working with fields, and Firebase use it by default. Anyway, the rest of the library doesnt need to be obfuscate. 

If you wanna avoid warns, I suggest the users to add the same line that you added in your code(There is no point to avoid the warning of all the library, or it will not be able to detect a problem in a future).
