### ISSUE TITLE
Is RxFirestore still on beta?

### ISSUE THREAD

**Issue by bernaferrari** [FrangSierra/Rx2Firebase#43]
Hi, I am new here and very confused. I saw on some post that Rx2Firebase 1.4 would contain Firestore.. however, the Firestore branch is behind by 10 commits and RxFirestore is there on master. Problem is, it isn't showing here and I'm not sure what is going on:

<img width="522" alt="screen shot 2018-01-25 at 20 09 22" src="https://user-images.githubusercontent.com/351125/35415242-0d5d12a4-020c-11e8-8345-3c37f88aba12.png">

**Comment by FrangSierra** [comment]
Rxfirestore was released with the normal library 2 days ago with the 1.4.0 version :) . I will delete the branch of RxFirestore later to avoid confusion.

Thank u for your feedback!

**Comment by bernaferrari** [comment]
Readme is still on 1.3, that might have been another point of confusion for me. Thanks!

**Comment by androidovshchik** [comment]
@FrangSierra please update readme with firestore
