### ISSUE TITLE
Firestore ObserveCollection

### ISSUE THREAD

**Issue by Junderwood93** [FrangSierra/Rx2Firebase#45]
Hi,

Are there plans to add a way to observe a snapshot of a query rather than just using .get()?

Basically looking for support for this:

`Query firestoreQueryRef = firestore.collection("users")
 firestoreQueryRef.addSnapshotListener(..)`

Thanks for all the good work!

**Comment by FrangSierra** [comment]
Do a PR and I will add the method to the library :) If not I will add it in the next release.

If you create a PR dont forget to add comments and format the code!

**Comment by garmax1** [comment]
Done in development branch

**Comment by FrangSierra** [comment]
Updated in last release
